 SELECT IMPRIME_COMPROBANTE.SOPNUMBE, IMPRIME_COMPROBANTE.SOPTYPE, IMPRIME_COMPROBANTE.user_id, IMPRIME_COMPROBANTE.address, IMPRIME_COMPROBANTE.shipping_address, IMPRIME_COMPROBANTE.PYMTRMID, IMPRIME_COMPROBANTE.DUEDATE, IMPRIME_COMPROBANTE.UNITPRCE, IMPRIME_COMPROBANTE.XTNDPRCE, IMPRIME_COMPROBANTE.LINEA, IMPRIME_COMPROBANTE.SUBTOTAL, IMPRIME_COMPROBANTE.TAXAMNT, IMPRIME_COMPROBANTE.DOCAMNT, IMPRIME_COMPROBANTE.DOCDATE, IMPRIME_COMPROBANTE.CUSTNAME, IMPRIME_COMPROBANTE.ORDENVTA, IMPRIME_COMPROBANTE.FECHAORDVTA, 
	IMPRIME_COMPROBANTE.img_url, INT_SOPLINE_DATA.ARTIC_NAME, IMPRIME_COMPROBANTE.LNITMSEQ, IMPRIME_COMPROBANTE.QUANTITY, IMPRIME_COMPROBANTE.PYMTRCVD, IMPRIME_COMPROBANTE.ACCTAMNT, IMPRIME_COMPROBANTE.CHEKBKID, IMPRIME_COMPROBANTE.CHEKNMBR, IMPRIME_COMPROBANTE.TRDISAMT, IMPRIME_COMPROBANTE.memo, IMPRIME_COMPROBANTE.sTabla, IMPRIME_COMPROBANTE.sello, IMPRIME_COMPROBANTE.fechahora, IMPRIME_COMPROBANTE.noCertificado, IMPRIME_COMPROBANTE.noAprobacion, IMPRIME_COMPROBANTE.anoAprobacion, IMPRIME_COMPROBANTE.formaDePago, IMPRIME_COMPROBANTE.tax_number, IMPRIME_COMPROBANTE.CURTEXT, IMPRIME_COMPROBANTE.cadenaOriginal,
	ITEMNMBR,
	imagenBinaria
 FROM   GMOPE.dbo.IMPRIME_COMPROBANTE_ELECTRONICO IMPRIME_COMPROBANTE 
 LEFT OUTER JOIN GMOPE.dbo.INT_SOPLINE_DATA_VIEW INT_SOPLINE_DATA 
 ON ((IMPRIME_COMPROBANTE.SOPTYPE=INT_SOPLINE_DATA.SOPTYPE) 
 AND (IMPRIME_COMPROBANTE.SOPNUMBE=INT_SOPLINE_DATA.SOPNUMBE)) 
 AND (IMPRIME_COMPROBANTE.LNITMSEQ=INT_SOPLINE_DATA.LNITMSEQ)
 WHERE  IMPRIME_COMPROBANTE.sTabla='SOP30200'
 and IMPRIME_COMPROBANTE.SOPNUMBE = '0000001'
 ORDER BY IMPRIME_COMPROBANTE.SOPTYPE, IMPRIME_COMPROBANTE.SOPNUMBE


--SELECT 'First test file', 
select *
from int_sopline_data
where sopnumbe = '0000001'

select *
from IV00101
where ITEMNMBR = 'PICTURE_ON_PAYMENT'
