USE arg10
GO

/****** Object:  View [dbo].[INT_SOPLINE_DATA_VIEW]    Script Date: 01/09/2017 10:08:03 a. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO





create VIEW [dbo].[INT_SOPLINE_DATA_VIEW] AS
SELECT A.SOPTYPE, A.SOPNUMBE, A.LNITMSEQ, ISNULL(B.ARTIC_NAME, '') ARTIC_NAME, ISNULL(B.APPPRCLST, 'none') APPPRCLST, 
ISNULL(B.ARTIC_DESC, '') ARTIC_DESC, ISNULL(B.BUY_NOTE, '') BUY_NOTE, ISNULL(B.COLL_NAME, '') COLL_NAME, 
ISNULL(B.ARTIC_INFO, '') ARTIC_INFO, ISNULL(B.USAGE_DESC, '') USAGE_DESC, ISNULL(B.USAGE_RIGHTS, '') USAGE_RIGHTS, 
ISNULL(B.MPUBDATE, 0) MPUBDATE, ISNULL(B.PUBEXPDATE, 0) PUBEXPDATE, ISNULL(B.MPUBCCODE, '') MPUBCCODE, ISNULL(B.DDTONINV, 0) DDTONINV
FROM SOP10200 A LEFT OUTER JOIN INT_SOPLINE_DATA B ON A.SOPTYPE = B.SOPTYPE AND A.SOPNUMBE = B.SOPNUMBE AND A.LNITMSEQ = B.LNITMSEQ
UNION
SELECT A.SOPTYPE, A.SOPNUMBE, A.LNITMSEQ, ISNULL(B.ARTIC_NAME, '') ARTIC_NAME, ISNULL(B.APPPRCLST, 'none') APPPRCLST, 
ISNULL(B.ARTIC_DESC, '') ARTIC_DESC, ISNULL(B.BUY_NOTE, '') BUY_NOTE, ISNULL(B.COLL_NAME, '') COLL_NAME, 
ISNULL(B.ARTIC_INFO, '') ARTIC_INFO, ISNULL(B.USAGE_DESC, '') USAGE_DESC, ISNULL(B.USAGE_RIGHTS, '') USAGE_RIGHTS, 
ISNULL(B.MPUBDATE, 0) MPUBDATE, ISNULL(B.PUBEXPDATE, 0) PUBEXPDATE, ISNULL(B.MPUBCCODE, '') MPUBCCODE, ISNULL(B.DDTONINV, 0) DDTONINV
FROM SOP30300 A LEFT OUTER JOIN INT_SOPLINE_DATA B ON A.SOPTYPE = B.SOPTYPE AND A.SOPNUMBE = B.SOPNUMBE AND A.LNITMSEQ = B.LNITMSEQ





GO


